version: '3'
services:
    nginx:
        image: 'nginx:stable'
        ports:
            - '80:80'
        volumes:
            - ./html:/usr/share/nginx/html
    jenkins:
        image: 'jenkins/jenkins:lts'
        ports:
            - '8080:8080'
            - '443:8443'
            - '50000:50000'
        volumes:
            - ./jenkins_jobs:/var/jenkins_home/jobs
            - ./html:/var/www/html

volumes:
    html:
        driver: local
    jenkins_jobs:
        driver: local